[package]
name = "numtoy-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "numtoy_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = "0.2"
pyo3 = { version = "0.28.3", features = ["extension-module"] }
cranelift-codegen = "0.131.1"
cranelift-frontend = "0.131.1"
cranelift-module = "0.131.1"
cranelift-jit = "0.131.1"
cranelift-native = "0.131.1"
wgpu = "24.0.0"
pollster = "0.3"

[build-dependencies]
cbindgen = "0.29.2"
